In [8]:
!pip install sqlalchemy

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.40-cp312-cp312-win_amd64.whl.metadata (9.9 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.2.1-cp312-cp312-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\amart\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (4.12.2)
Downloading sqlalchemy-2.0.40-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.1 MB 932.9 kB/s eta 0:00:02
   -------------- ------------------------- 0.8/2.1 MB 1.2 MB/s eta 0:00:02
   -------------- ------------------------- 0.8/2.1 MB 1.2 MB/s eta 0:00:02
   ------------------- -------------------- 1.0/2.1 MB 882.6 kB/s eta 0:00:02
   ------------------- -------------------- 1.0/2.1 MB 882.6 kB/s eta 0:00:02
   ------------------------ --------------- 1.3/2.1 MB 894.7 kB/s eta 0:00:01
   ------------------------ --------------- 1.3/2.1 MB 894.7 kB/s eta 0:00:01
   ----------------------------- ---------- 1.6/2.1 MB 806.6 kB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 845.6 kB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 895.0 kB/s eta 0:00:00
Downloading greenlet-3.2.1-cp312-cp312-win_amd64.whl (296 kB)
Installing collected packages: greenlet, sqlalchemy
Successfully installed greenlet-3.2.1 sqlalchemy-2.0.40

[notice] A new release of pip is available: 24.3.1 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
!pip install pymysql

Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1

[notice] A new release of pip is available: 24.3.1 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
import pandas as pd
from sqlalchemy import create_engine

# Define your connection details
username = 'root'
password = 'root'
host = 'localhost'
port = '3306'
database = 'amazon_scraper'

# Create the SQLAlchemy engine
engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# Load the `products` table into a DataFrame
products_df = pd.read_sql('SELECT * FROM products', con=engine)

# Preview the data
print("✅ Data loaded from MySQL:")
display(products_df.head())

✅ Data loaded from MySQL:

,id,asin,url,title,price,discount,rating,review_count,brand,category,created_at,updated_at
0,1,B0DP7BZ8FD,https://www.amazon.in/Lenovo-IdeaPad-i5-12450H...,"Lenovo IdeaPad Slim 3, Intel Core i5-12450H, 1...",49090.0,31%,3.9,513.0,‎Lenovo,laptops,2025-04-30 16:04:24,2025-04-30 16:04:24
1,2,B0D5DFR78J,https://www.amazon.in/ASUS-15-6-inch-GeForce-G...,"ASUS TUF Gaming A15, AMD Ryzen 7 7435HS Gaming...",67990.0,19%,3.9,462.0,‎ASUS,laptops,2025-04-30 16:04:33,2025-04-30 16:04:33
2,3,B0DVGQPW13,https://www.amazon.in/Lenovo-39-62cm-Antiglare...,"Lenovo V15 AMD Ryzen 3 7320U 15.6"" (39.62cm) F...",25990.0,49%,3.8,33.0,‎Lenovo,laptops,2025-04-30 16:04:39,2025-04-30 16:04:39
3,4,B08N5W4NNB,https://aax-eu.amazon.in/x/c/JM88vS5tjJ4uCaWns...,"Apple MacBook Air Laptop: Apple M1 chip, 13.3-...",64990.0,28%,4.6,6678.0,‎Apple,laptops,2025-04-30 16:04:50,2025-04-30 16:04:50
4,5,B0D3HG5CMG,https://www.amazon.in/HP-Laptop-15-6-inch-Grap...,"HP 15, AMD Ryzen 3 7320U Laptop (8GB LPDDR5, 5...",29990.0,35%,4.1,1529.0,‎HP,laptops,2025-04-30 16:04:57,2025-04-30 16:04:57

In [17]:
# Display the first 5 rows
print("Sample data:")
display(products_df.head())

# Display basic info
print("\nData types and nulls:")
products_df.info()

# Check for missing values
print("\nMissing values per column:")
print(products_df.isnull().sum())

Sample data:

,id,asin,url,title,price,discount,rating,review_count,brand,category,created_at,updated_at
0,1,B0DP7BZ8FD,https://www.amazon.in/Lenovo-IdeaPad-i5-12450H...,"Lenovo IdeaPad Slim 3, Intel Core i5-12450H, 1...",49090.0,31%,3.9,513.0,‎Lenovo,laptops,2025-04-30 16:04:24,2025-04-30 16:04:24
1,2,B0D5DFR78J,https://www.amazon.in/ASUS-15-6-inch-GeForce-G...,"ASUS TUF Gaming A15, AMD Ryzen 7 7435HS Gaming...",67990.0,19%,3.9,462.0,‎ASUS,laptops,2025-04-30 16:04:33,2025-04-30 16:04:33
2,3,B0DVGQPW13,https://www.amazon.in/Lenovo-39-62cm-Antiglare...,"Lenovo V15 AMD Ryzen 3 7320U 15.6"" (39.62cm) F...",25990.0,49%,3.8,33.0,‎Lenovo,laptops,2025-04-30 16:04:39,2025-04-30 16:04:39
3,4,B08N5W4NNB,https://aax-eu.amazon.in/x/c/JM88vS5tjJ4uCaWns...,"Apple MacBook Air Laptop: Apple M1 chip, 13.3-...",64990.0,28%,4.6,6678.0,‎Apple,laptops,2025-04-30 16:04:50,2025-04-30 16:04:50
4,5,B0D3HG5CMG,https://www.amazon.in/HP-Laptop-15-6-inch-Grap...,"HP 15, AMD Ryzen 3 7320U Laptop (8GB LPDDR5, 5...",29990.0,35%,4.1,1529.0,‎HP,laptops,2025-04-30 16:04:57,2025-04-30 16:04:57

Data types and nulls:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 947 entries, 0 to 946
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            947 non-null    int64
 1   asin          947 non-null    object
 2   url           947 non-null    object
 3   title         763 non-null    object
 4   price         763 non-null    float64
 5   discount      758 non-null    object
 6   rating        745 non-null    float64
 7   review_count  761 non-null    float64
 8   brand         418 non-null    object
 9   category      947 non-null    object
 10  created_at    947 non-null    datetime64[ns]
 11  updated_at    947 non-null    datetime64[ns]
dtypes: datetime64[ns](2), float64(3), int64(1), object(6)
memory usage: 88.9+ KB

Missing values per column:
id                0
asin              0
url               0
title           184
price           184
discount        189
rating          202
review_count    186
brand           529
category          0
created_at        0
updated_at        0
dtype: int64

In [18]:
import re

# 1. Clean ASIN
products_df['asin'] = products_df['asin'].str.strip()
asin_duplicates = products_df['asin'].duplicated().sum()
print(f" Duplicate ASINs found: {asin_duplicates}")

# Drop rows with duplicate or null ASINs
products_df.drop_duplicates(subset='asin', inplace=True)
products_df.dropna(subset=['asin'], inplace=True)

# 2. Validate URL (must start with http and contain 'amazon')
products_df['url_valid'] = products_df['url'].apply(lambda x: x.startswith('http') and 'amazon' in x)
invalid_urls = products_df[~products_df['url_valid']]
print(f" Invalid URLs found: {len(invalid_urls)}")

# Drop invalid URLs (optional)
products_df = products_df[products_df['url_valid']].drop(columns='url_valid')

# 3. Clean and normalize title
products_df['title'] = products_df['title'].fillna('').str.lower().str.strip()
products_df['title'] = products_df['title'].apply(lambda x: re.sub(r'[^a-zA-Z0-9\s\-.,]', '', x))  # Remove unwanted chars

# Preview cleaned columns
print("\n Cleaned columns preview:")
display(products_df[['asin', 'url', 'title']].head())

 Duplicate ASINs found: 0
 Invalid URLs found: 0

 Cleaned columns preview:

,asin,url,title
0,B0DP7BZ8FD,https://www.amazon.in/Lenovo-IdeaPad-i5-12450H...,"lenovo ideapad slim 3, intel core i5-12450h, 1..."
1,B0D5DFR78J,https://www.amazon.in/ASUS-15-6-inch-GeForce-G...,"asus tuf gaming a15, amd ryzen 7 7435hs gaming..."
2,B0DVGQPW13,https://www.amazon.in/Lenovo-39-62cm-Antiglare...,lenovo v15 amd ryzen 3 7320u 15.6 39.62cm fhd ...
3,B08N5W4NNB,https://aax-eu.amazon.in/x/c/JM88vS5tjJ4uCaWns...,"apple macbook air laptop apple m1 chip, 13.3-i..."
4,B0D3HG5CMG,https://www.amazon.in/HP-Laptop-15-6-inch-Grap...,"hp 15, amd ryzen 3 7320u laptop 8gb lpddr5, 51..."

In [19]:
# 1. Clean price (already float, just round for consistency)
products_df['price'] = pd.to_numeric(products_df['price'], errors='coerce').round(2)

# 2. Clean discount – remove '%' and convert to float
products_df['discount'] = products_df['discount'].str.replace('%', '', regex=False)
products_df['discount'] = pd.to_numeric(products_df['discount'], errors='coerce').round(2)

# 3. Clean rating – filter values between 0 and 5
products_df['rating'] = pd.to_numeric(products_df['rating'], errors='coerce')
products_df.loc[(products_df['rating'] > 5) | (products_df['rating'] < 0), 'rating'] = None

# 4. Clean review_count – force to integer, allow NaNs
products_df['review_count'] = pd.to_numeric(products_df['review_count'], errors='coerce').dropna()
products_df['review_count'] = products_df['review_count'].astype('Int64')  # nullable integer type

# 5. Clean brand – normalize text, do not fill missing
products_df['brand'] = products_df['brand'].str.strip().str.lower()

# Show summary of cleaned columns
print("Summary after cleaning:")
print(products_df[['price', 'discount', 'rating', 'review_count', 'brand']].describe(include='all'))

# Optional: Check how many rows have missing values now (just info, no deletion)
print("\nMissing value counts (post-cleaning):")
print(products_df[['price', 'discount', 'rating', 'review_count', 'brand']].isnull().sum())

Summary after cleaning:
                price    discount      rating  review_count   brand
count      763.000000  758.000000  745.000000         761.0     418
unique            NaN         NaN         NaN          <NA>     107
top               NaN         NaN         NaN          <NA>  ‎noise
freq              NaN         NaN         NaN          <NA>      31
mean     14744.932228   48.191293    3.957584   4952.541393     NaN
std      29911.920874   24.211564    0.388476  13960.966826     NaN
min         99.000000    3.000000    1.000000           1.0     NaN
25%        999.000000   27.000000    3.800000         145.0     NaN
50%       2640.000000   46.000000    4.000000         544.0     NaN
75%      17940.000000   70.750000    4.200000        3640.0     NaN
max     500990.000000   94.000000    5.000000      138403.0     NaN

Missing value counts (post-cleaning):
price           184
discount        189
rating          202
review_count    186
brand           529
dtype: int64

In [20]:
# 1. Normalize category
products_df['category'] = products_df['category'].str.strip().str.lower()

# Optional: Inspect unique categories
print("Unique categories:")
print(products_df['category'].value_counts())

# 2. Convert created_at and updated_at to datetime if not already
products_df['created_at'] = pd.to_datetime(products_df['created_at'], errors='coerce')
products_df['updated_at'] = pd.to_datetime(products_df['updated_at'], errors='coerce')

# 3. Check for invalid or future timestamps
from datetime import datetime

now = pd.Timestamp.now()
future_created = products_df[products_df['created_at'] > now]
future_updated = products_df[products_df['updated_at'] > now]

print(f"\n Future 'created_at' rows: {len(future_created)}")
print(f"Future 'updated_at' rows: {len(future_updated)}")

# Preview time differences if needed
products_df['time_diff'] = (products_df['updated_at'] - products_df['created_at']).dt.total_seconds() / 3600

print("\n Time difference (in hours) between update and creation — stats:")
print(products_df['time_diff'].describe())

Unique categories:
category
smartphones         280
laptops             272
smartwatches        238
wireless_earbuds    157
Name: count, dtype: int64

 Future 'created_at' rows: 0
Future 'updated_at' rows: 0

 Time difference (in hours) between update and creation — stats:
count    947.000000
mean       0.006485
std        0.044747
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        0.630278
Name: time_diff, dtype: float64

In [26]:
specs_df = pd.read_sql('SELECT * FROM specifications', con=engine)

In [27]:
# Display sample
print("Sample specifications data:")
display(specs_df.head())

# Show basic info
print("\nData types and nulls:")
specs_df.info()

# Missing values
print("\nMissing values per column:")
print(specs_df.isnull().sum())

# Clean spec_name and spec_value
specs_df['spec_name'] = specs_df['spec_name'].astype(str).str.strip().str.lower()
specs_df['spec_value'] = specs_df['spec_value'].astype(str).str.strip()

# Drop rows with missing product_id or spec_name
specs_df = specs_df.dropna(subset=['product_id', 'spec_name'])

# Check for duplicates
duplicates = specs_df.duplicated(subset=['product_id', 'spec_name']).sum()
print(f"\nDuplicate (product_id, spec_name) pairs: {duplicates}")

# Optional: Drop duplicates if needed
# specs_df = specs_df.drop_duplicates(subset=['product_id', 'spec_name'])

# Preview cleaned specs
print("\nCleaned specifications preview:")
display(specs_df.head())

Sample specifications data:

   id  product_id     spec_name              spec_value
0   1           1         Brand                 ‎Lenovo
1   2           1  Manufacturer                 ‎Lenovo
2   3           1        Series                ‎IdeaPad
3   4           1        Colour  ‎i5-12th | Office 2024
4   5           1   Form Factor           ‎Thin & Light

Data types and nulls:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22712 entries, 0 to 22711
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          22712 non-null  int64
 1   product_id  22712 non-null  int64
 2   spec_name   22712 non-null  object
 3   spec_value  22712 non-null  object
dtypes: int64(2), object(2)
memory usage: 709.9+ KB

Missing values per column:
id            0
product_id    0
spec_name     0
spec_value    0
dtype: int64

Duplicate (product_id, spec_name) pairs: 0

Cleaned specifications preview:

   id  product_id     spec_name              spec_value
0   1           1         brand                 ‎Lenovo
1   2           1  manufacturer                 ‎Lenovo
2   3           1        series                ‎IdeaPad
3   4           1        colour  ‎i5-12th | Office 2024
4   5           1   form factor           ‎Thin & Light

In [28]:
# Create a dict to store category-wise pivoted specs
category_specs = {}

# Get distinct categories
categories = products_df['category'].dropna().unique()

# For each category, pivot specs only for products of that category
for cat in categories:
    cat_products = products_df[products_df['category'] == cat]
    cat_specs = specs_df[specs_df['product_id'].isin(cat_products['id'])]

    # Pivot
    pivot = cat_specs.pivot_table(
        index='product_id',
        columns='spec_name',
        values='spec_value',
        aggfunc='first'
    ).reset_index()

    # Clean column names
    pivot.columns.name = None
    pivot.columns = [col.strip().replace(" ", "_") for col in pivot.columns]
    
    # Merge with category-specific product data
    merged = cat_products.merge(pivot, left_on='id', right_on='product_id', how='left')
    
    category_specs[cat] = merged  # Store

    print(f"\n Processed category: {cat}")
    print(f"Columns: {list(merged.columns)}")
    display(merged.head(2))

 Processed category: laptops
Columns: ['id', 'asin_x', 'url', 'title', 'price', 'discount', 'rating', 'review_count', 'brand_x', 'category', 'created_at', 'updated_at', 'time_diff', 'product_id', '-_sugars', 'age_range_(description)', 'allergen_information', 'annual_energy_consumption', 'are_batteries_included', 'asin_y', 'asin\n____________________________________\u200f', 'aspect_ratio', 'assembly_required', 'assembly_type', 'audio_details', 'audio_driver_size', 'audio_driver_type', 'audio_output_type', 'average_battery_life_(in_hours)', 'average_battery_standby_life_(in_hours)', 'base_material', 'base_type', 'batteries', 'batteries_included', 'batteries_required', 'battery_average_life', 'battery_average_life_standby', 'battery_cell_composition', 'best_sellers_rank', 'brand_y', 'capacity', 'carbohydrate', 'cellular_technology', 'chipset_type', 'color', 'colour', 'colour_screen', 'compatible_devices', 'computer_memory_type', 'connectivity_protocol', 'connectivity_type', 'connector_type', 'control_method', 'controller_type', 'country_of_origin', 'country_of_origin\n____________________________________\u200f', 'customer_reviews', 'data_link_protocol', 'data_transfer_rate', 'date_first_available', 'date_first_available\n____________________________________\u200f', 'department\n____________________________________\u200f', 'device_interface_-_primary', 'device_type', 'digital_storage_capacity', 'dimensions\n____________________________________\u200f', 'display_technology', 'display_type', 'does_it_contain_liquid?', 'educational_objective(s)', 'energy_(kcal)', 'energy_efficiency', 'fat', 'features', 'finish_type', 'flash_memory_installed_size', 'flash_memory_type', 'form', 'form_factor', 'front_webcam_resolution', 'furniture_finish', 'generic_name', 'generic_name\n____________________________________\u200f', 'graphics_card_description', 'graphics_card_interface', 'graphics_card_ram_size', 'graphics_chipset_brand', 'graphics_coprocessor', 'graphics_ram_type', 'gsm_frequencies', 'hand_orientation', 'hard_disk_description', 'hard_disk_rotational_speed', 'hard_drive_interface', 'hard_drive_size', 'hardcover\n____________________________________\u200f', 'hardware_interface', 'hardware_platform', 'has_audio_recording_capabilities', 'has_auto_focus', 'has_image_stabilisation', 'head_style', 'image_stabilization_technology', 'imported_by', 'importer', 'importer\n____________________________________\u200f', 'included_components', 'included_components\n____________________________________\u200f', 'includes_rechargeable_battery', 'ingredient_type', 'ingredients', 'installation_type', 'is_discontinued_by_manufacturer\n____________________________________\u200f', 'is_there_a_timer?', 'is_waterproof', 'item_dimensions_l_x_w_x_h', 'item_dimensions_lxwxh', 'item_dimensions_lxwxh\n____________________________________\u200f', 'item_height', 'item_model_number', 'item_model_number\n____________________________________\u200f', 'item_package_quantity', 'item_part_number', 'item_part_number\n____________________________________\u200f', 'item_weight', 'item_weight\n____________________________________\u200f', 'item_width', 'keyboard_description', 'language\n____________________________________\u200f', 'lens_type', 'lithium_battery_energy_content', 'lithium_battery_weight', 'manufacturer', 'manufacturer\n____________________________________\u200f', 'manufacturer_recommended_age', 'material', 'material_type(s)', 'mattress_comfort', 'maximum_height', 'maximum_memory_supported', 'maximum_resolution', 'maximum_weight_recommendation', 'memory_clock_speed', 'memory_slots_available', 'memory_storage_capacity', 'memory_technology', 'microphone_format', 'min_focal_length', 'minimum_height', 'model', 'model_name', 'model_number', 'model_year', 'mounting_hardware', 'mounting_type', 'movement_detection_technology', 'net_quantity', 'net_quantity\n____________________________________\u200f', 'noise_level', 'notebook_display_technology', 'number_of_ethernet_ports', 'number_of_game_players', 'number_of_hdmi_ports', 'number_of_items', 'number_of_lithium_ion_cells', 'number_of_lithium_metal_cells', 'number_of_pieces', 'number_of_ports', 'number_of_puzzle_pieces', 'number_of_shelves', 'number_of_usb_2_ports', 'number_of_usb_2.0_ports', 'number_of_usb_3.0_ports', 'operating_system', 'optical_drive_type', 'optical_sensor_resolution', 'other_display_features', 'package_dimensions', 'package_information', 'packer', 'packer\n____________________________________\u200f', 'part_number', 'power_source', 'primary_material', 'processor_brand', 'processor_count', 'processor_model_number', 'processor_speed', 'processor_type', 'product_care_instructions', 'product_dimensions', 'product_dimensions\n____________________________________\u200f', 'product_grade', 'programmable_buttons', 'protein', 'publisher\n____________________________________\u200f', 'publisher_code', 'ram_memory_installed_size', 'ram_memory_maximum_size', 'ram_memory_technology', 'ram_size', 'reading_age\n____________________________________\u200f', 'rear_webcam_resolution', 'recommended_uses_for_product', 'refresh_rate', 'release_date\n____________________________________\u200f', 'resolution', 'screen_resolution', 'series', 'serving_size', 'shipping_weight', 'size', 'software_included', 'speaker_description', 'speaker_size', 'speaker_type', 'special_feature', 'special_features', 'specialty', 'specific_uses_for_product', 'standing_screen_display_size', 'storage_instructions', 'style', 'subwoofer_connectivity_technology', 'subwoofer_diameter', 'supports_bluetooth_technology', 'surround_sound_channel_configuration', 'target_gender', 'tech_spec_battery_description_toys', 'top_color', 'top_material_type', 'total_usb_ports', 'tweeter_diameter', 'type_of_cable_or_wire', 'video_output', 'voltage', 'volume', 'warranty_type', 'wattage', 'weight', 'what_is_in_the_box?', 'whats_in_the_box', 'wireless_communication_technology', 'wireless_type', 'working_surface_diagonal_length']

,id,asin_x,url,title,price,discount,rating,review_count,brand_x,category,...,voltage,volume,warranty_type,wattage,weight,what_is_in_the_box?,whats_in_the_box,wireless_communication_technology,wireless_type,working_surface_diagonal_length
0,1,B0DP7BZ8FD,https://www.amazon.in/Lenovo-IdeaPad-i5-12450H...,"lenovo ideapad slim 3, intel core i5-12450h, 1...",49090.0,31.0,3.9,513,‎lenovo,laptops,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,‎802.11a/b/g/n/ac,NaN
1,2,B0D5DFR78J,https://www.amazon.in/ASUS-15-6-inch-GeForce-G...,"asus tuf gaming a15, amd ryzen 7 7435hs gaming...",67990.0,19.0,3.9,462,‎asus,laptops,...,‎240 Volts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"‎Bluetooth, 802.11bgn",NaN

 Processed category: smartphones
Columns: ['id', 'asin_x', 'url', 'title', 'price', 'discount', 'rating', 'review_count', 'brand_x', 'category', 'created_at', 'updated_at', 'time_diff', 'product_id', 'access_location', 'annual_energy_consumption', 'asin_y', 'audio_jack', 'batteries', 'batteries_included', 'batteries_required', 'battery_capacity', 'battery_cell_composition', 'battery_description', 'battery_power_rating', 'best_sellers_rank', 'brand_y', 'capacity', 'cellular_technology', 'certification', 'colour', 'colours_displayed', 'connectivity_technologies', 'connector_type', 'control_console', 'country_of_origin', 'customer_reviews', 'date_first_available', 'device_interface_-_primary', 'digital_storage_capacity', 'display_technology', 'display_type', 'features', 'flash_memory_installed_size', 'form_factor', 'fuel_type', 'generic_name', 'gps', 'importer', 'included_components', 'installation_type', 'item_dimensions_lxwxh', 'item_model_number', 'item_part_number', 'item_weight', 'manufacturer', 'material', 'maximum_rotational_speed', 'memory_slots_available', 'memory_storage_capacity', 'model', 'model_name', 'model_year', 'mounting_hardware', 'net_quantity', 'number_of_items', 'number_of_standard_cycles', 'operating_system', 'optical_sensor_resolution', 'os', 'other_camera_features', 'other_display_features', 'package_dimensions', 'packer', 'part_number', 'phone_standby_time_(with_data)', 'phone_talk_time', 'processor_brand', 'processor_speed', 'processor_type', 'product_dimensions', 'ram', 'ram_memory_installed_size', 'resolution', 'special_features', 'standing_screen_display_size', 'video_capture_resolution', 'voltage', 'wattage', 'whats_in_the_box', 'wireless_communication_technologies']

,id,asin_x,url,title,price,discount,rating,review_count,brand_x,category,...,ram,ram_memory_installed_size,resolution,special_features,standing_screen_display_size,video_capture_resolution,voltage,wattage,whats_in_the_box,wireless_communication_technologies
0,274,B0DFY3XCB6,https://www.amazon.in/Samsung-Storage-Display-...,"samsung galaxy m05 mint green, 4gb ram, 64 gb ...",6499.0,35.0,4.0,2965,None,smartphones,...,‎4 GB,NaN,‎720 x 1600,"‎Fast Charging Support, Dual SIM, Expandable M...",NaN,NaN,NaN,NaN,"‎SIM Ejector Pin, USB Cable (Type C-to-C), Sma...",‎Cellular
1,275,B07WGPJWQL,https://www.amazon.in/Y29-Glacier-Storage-Addi...,"vivo y29 5g glacier blue, 6gb ram, 128gb stora...",15499.0,14.0,4.0,84,None,smartphones,...,NaN,NaN,‎1608 x 720,"‎Bluetooth Enabled, Basic Phone, Dual SIM, Cam...",NaN,NaN,NaN,NaN,"‎Power Adapter, SIM Tray Ejector, Phone Case, ...",NaN

 Processed category: wireless_earbuds
Columns: ['id', 'asin_x', 'url', 'title', 'price', 'discount', 'rating', 'review_count', 'brand_x', 'category', 'created_at', 'updated_at', 'time_diff', 'product_id', 'age_range_(description)', 'are_batteries_included', 'asin_y', 'audio_driver_size', 'audio_driver_type', 'audio_latency', 'batteries', 'batteries_included', 'batteries_required', 'battery_average_life', 'battery_cell_composition', 'battery_life', 'battery_type', 'best_sellers_rank', 'bluetooth_range', 'bluetooth_version', 'brand_y', 'cable_feature', 'carrying_case_battery_average_life', 'carrying_case_battery_capacity', 'carrying_case_battery_charging_time', 'carrying_case_color', 'carrying_case_height', 'carrying_case_length', 'carrying_case_material', 'carrying_case_weight', 'carrying_case_width', 'cartoon_character', 'charging_time', 'colour', 'compatible_devices', 'connectivity_technology', 'connector', 'connector_type', 'control_method', 'control_type', 'controller_type', 'country_of_origin', 'customer_package_type', 'customer_reviews', 'date_first_available', 'does_it_contain_liquid?', 'earpiece_shape', 'features', 'form_factor', 'frequency_range', 'frequency_response', 'generic_name', 'global_trade_identification_number', 'hardware_platform', 'headphones_form_factor', 'headphones_jack', 'imported_by', 'importer', 'included_components', 'includes_rechargeable_battery', 'is_autographed', 'item_dimensions_lxwxh', 'item_height', 'item_model_number', 'item_weight', 'item_width', 'lithium_battery_energy_content', 'manufacturer', 'material', 'maximum_operating_distance', 'microphone_format', 'model', 'model_name', 'model_year', 'mounting_hardware', 'net_quantity', 'noise_control', 'number_of_items', 'number_of_lithium_ion_cells', 'number_of_power_levels', 'other_display_features', 'packer', 'power_source', 'product_dimensions', 'recommended_uses_for_product', 'sensitivity', 'series_number', 'size', 'special_features', 'specific_uses_for_product', 'style', 'supports_bluetooth_technology', 'theme', 'upc', 'voltage', 'water_resistance_level', 'whats_in_the_box', 'wireless_communication_technology']

,id,asin_x,url,title,price,discount,rating,review_count,brand_x,category,...,special_features,specific_uses_for_product,style,supports_bluetooth_technology,theme,upc,voltage,water_resistance_level,whats_in_the_box,wireless_communication_technology
0,554,B0C8JB3G5W,https://www.amazon.in/OnePlus-Wireless-Earbuds...,oneplus nord buds 2r true wireless in ear earb...,1799.0,22.0,4.2,24466,None,wireless_earbuds,...,"‎Oneplus Fast Pair, Dolby Atmos Support, Dirac...",NaN,‎Nord Buds 2r,NaN,‎Fantasy,NaN,NaN,‎Water Resistant,NaN,‎Bluetooth
1,556,B0CZ3ZPD8B,https://www.amazon.in/boAt-Airdopes-311-Pro-Lo...,"boat airdopes 311 pro, 50hrs battery, fast cha...",799.0,84.0,3.4,3646,None,wireless_earbuds,...,‎Built-In Voice Assistant,NaN,‎50 Hours,NaN,NaN,NaN,NaN,‎Water Resistant,NaN,‎Bluetooth

 Processed category: smartwatches
Columns: ['id', 'asin_x', 'url', 'title', 'price', 'discount', 'rating', 'review_count', 'brand_x', 'category', 'created_at', 'updated_at', 'time_diff', 'product_id', 'are_batteries_included', 'are_batteries_included?', 'asin_y', 'asin\n____________________________________\u200f', 'average_battery_life_(in_hours)', 'batteries', 'batteries\n____________________________________\u200f', 'batteries_included', 'batteries_required', 'battery_average_life', 'battery_capacity', 'battery_cell_composition', 'battery_charge_time_(in_hours)', 'battery_description', 'battery_life', 'battery_power_rating', 'best_sellers_rank', 'brand_y', 'cable_interface', 'cable_type', 'cellular_technology', 'charging_time', 'colour', 'colour_screen', 'compatible_device', 'compatible_devices', 'compatible_phone_models', 'connectivity_technologies', 'connectivity_type', 'connector_gender', 'connector_type', 'country_of_origin', 'country_of_origin\n____________________________________\u200f', 'customer_package_type', 'customer_reviews', 'data_transfer_rate', 'date_first_available', 'date_first_available\n____________________________________\u200f', 'department\n____________________________________\u200f', 'device_interface_-_primary', 'display_technology', 'display_type', 'does_it_contain_liquid?', 'features', 'generic_name', 'generic_name\n____________________________________\u200f', 'importer', 'importer\n____________________________________\u200f', 'included_components', 'included_components\n____________________________________\u200f', 'includes_rechargeable_battery', 'indoor/outdoor_usage', 'item_dimensions_lxwxh', 'item_dimensions_lxwxh\n____________________________________\u200f', 'item_height', 'item_model_number', 'item_model_number\n____________________________________\u200f', 'item_part_number\n____________________________________\u200f', 'item_weight', 'item_weight\n____________________________________\u200f', 'item_width', 'lithium_battery_energy_content', 'lithium_battery_weight', 'manufacturer', 'manufacturer\n____________________________________\u200f', 'material', 'memory_storage_capacity', 'model', 'model_name', 'model_number', 'model_year', 'mounting_hardware', 'mounting_type', 'net_quantity', 'net_quantity\n____________________________________\u200f', 'number_of_items', 'number_of_lithium_ion_cells', 'number_of_lithium_metal_cells', 'number_of_memory_sticks', 'number_of_pins', 'number_of_ports', 'operating_system', 'other_display_features', 'package_dimensions', 'package_dimensions\n____________________________________\u200f', 'packer', 'packer\n____________________________________\u200f', 'power_source', 'product_dimensions', 'product_dimensions\n____________________________________\u200f', 'ram_memory_installed_size', 'recommended_uses_for_product', 'resolution', 'screen_size', 'sensor_type', 'series', 'shape', 'special_feature', 'special_features', 'specification_met', 'standing_screen_display_size', 'total_usb_ports', 'upc', 'voltage', 'wattage', 'whats_in_the_box', 'wireless_carrier', 'wireless_type']

,id,asin_x,url,title,price,discount,rating,review_count,brand_x,category,...,special_features,specification_met,standing_screen_display_size,total_usb_ports,upc,voltage,wattage,whats_in_the_box,wireless_carrier,wireless_type
0,860,B0CQ4J4YFL,https://www.amazon.in/Noise-Smartwatch-Calling...,noise twist go round dial smartwatch with bt c...,1799.0,70.0,3.9,17678,‎noise,smartwatches,...,NaN,NaN,‎1.38 Inches,NaN,NaN,NaN,‎240 Watts,NaN,‎Unlocked,‎Bluetooth
1,861,B0CQ4JT6NT,https://www.amazon.in/Noise-Smartwatch-Calling...,,NaN,NaN,NaN,<NA>,None,smartwatches,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
images_df = pd.read_sql('SELECT * FROM images', con=engine)

In [32]:
# Display sample data
print(" Sample images data:")
display(images_df.head())

# Info & nulls
print("\n Data types and missing values:")
images_df.info()
print("\n Missing values per column:")
print(images_df.isnull().sum())

# Clean: Strip whitespace and lowercase URLs (optional)
images_df['image_url'] = images_df['image_url'].astype(str).str.strip()

# Remove completely missing URLs or product_id
images_df = images_df.dropna(subset=['product_id', 'image_url'])

# Ensure position is integer
images_df['position'] = pd.to_numeric(images_df['position'], errors='coerce').fillna(0).astype(int)

# Check for duplicates
duplicate_images = images_df.duplicated(subset=['product_id', 'image_url', 'position']).sum()
print(f"\n Duplicate (product_id, image_url, position): {duplicate_images}")

 Sample images data:

   id  product_id                                          image_url  position
0   1           1  https://m.media-amazon.com/images/I/81Tj8G57-W...         0
1   2           1  https://m.media-amazon.com/images/I/61gWo7sMzp...         1
2   3           1  https://m.media-amazon.com/images/I/81nCNmgtLH...         2
3   4           1  https://m.media-amazon.com/images/I/61qDZQ6NOC...         3
4   5           1  https://m.media-amazon.com/images/I/61zp01Wwse...         4

 Data types and missing values:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26938 entries, 0 to 26937
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          26938 non-null  int64
 1   product_id  26938 non-null  int64
 2   image_url   26938 non-null  object
 3   position    26938 non-null  int64
dtypes: int64(3), object(1)
memory usage: 841.9+ KB

 Missing values per column:
id            0
product_id    0
image_url     0
position      0
dtype: int64

 Duplicate (product_id, image_url, position): 0

In [33]:
# Filter for position = 1
primary_images = images_df[images_df['position'] == 1][['product_id', 'image_url']]

# Rename for clarity
primary_images = primary_images.rename(columns={'image_url': 'primary_image'})

# Join to products_df
products_with_images = products_df.merge(primary_images, left_on='id', right_on='product_id', how='left')

print("\n Products with primary image:")
display(products_with_images[['title', 'primary_image']].head())

 Products with primary image:

,title,primary_image
0,"lenovo ideapad slim 3, intel core i5-12450h, 1...",https://m.media-amazon.com/images/I/61gWo7sMzp...
1,"asus tuf gaming a15, amd ryzen 7 7435hs gaming...",https://m.media-amazon.com/images/I/61DBwMU6Qy...
2,lenovo v15 amd ryzen 3 7320u 15.6 39.62cm fhd ...,https://m.media-amazon.com/images/I/51flR80qeB...
3,"apple macbook air laptop apple m1 chip, 13.3-i...",https://m.media-amazon.com/images/I/71-6roO29A...
4,"hp 15, amd ryzen 3 7320u laptop 8gb lpddr5, 51...",https://m.media-amazon.com/images/I/81Avu7s+J1...

In [38]:
from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

# Define the base class for the models
Base = declarative_base()

# Define Product model
class Product(Base):
    __tablename__ = 'products'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    asin = Column(String(50), unique=True, nullable=False)
    title = Column(String(255), nullable=False)
    price = Column(Float, nullable=True)
    discount = Column(Float, nullable=True)
    rating = Column(Float, nullable=True)
    review_count = Column(Integer, nullable=True)
    brand = Column(String(100), nullable=True)
    category = Column(String(100), nullable=True)
    created_at = Column(DateTime, nullable=True)
    updated_at = Column(DateTime, nullable=True)
    primary_image = Column(String(255), nullable=True)

# Define Specification model
class Specification(Base):
    __tablename__ = 'specifications'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    product_id = Column(Integer, nullable=False)
    spec_name = Column(String(100), nullable=False)
    spec_value = Column(String(255), nullable=True)

# Define Image model
class Image(Base):
    __tablename__ = 'images'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    product_id = Column(Integer, nullable=False)
    image_url = Column(String(255), nullable=False)
    position = Column(Integer, nullable=False)

# Create the engine for the processed database
processed_db_url = "mysql+pymysql://root:root@localhost:3306/amazon_scraper_processed"
engine = create_engine(processed_db_url)

# Create the tables in the new database (if they don't already exist)
Base.metadata.create_all(engine)

# Create a session for adding data
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
session = SessionLocal()

# The rest of your code for saving data remains unchanged
# Save processed products data
for index, row in products_df.iterrows():
    product = Product(
        asin=row['asin'],
        title=row['title'],
        price=row['price'],
        discount=row['discount'],
        rating=row['rating'],
        review_count=row['review_count'],
        brand=row['brand'],
        category=row['category'],
        created_at=row['created_at'],
        updated_at=row['updated_at'],
        primary_image=row.get('primary_image', None)  # Handle missing primary image
    )
    session.add(product)

# Commit the changes to the products table
session.commit()

# Save processed specifications data
for index, row in specs_df.iterrows():
    specification = Specification(
        product_id=row['product_id'],
        spec_name=row['spec_name'],
        spec_value=row['spec_value']
    )
    session.add(specification)

# Commit the changes to the specifications table
session.commit()

# Save processed images data
for index, row in images_df.iterrows():
    image = Image(
        product_id=row['product_id'],
        image_url=row['image_url'],
        position=row['position']
    )
    session.add(image)

# Commit the changes to the images table
session.commit()

# Close the session
session.close()

print("✅ Processed data successfully saved to the 'amazon_scraper_processed' database.")

C:\Users\amart\AppData\Local\Temp\ipykernel_15620\1164285962.py:6: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()

ProgrammingError: (pymysql.err.ProgrammingError) nan can not be used with MySQL
[SQL: INSERT INTO products (asin, title, price, discount, rating, review_count, brand, category, created_at, updated_at, primary_image) VALUES (%(asin)s, %(title)s, %(price)s, %(discount)s, %(rating)s, %(review_count)s, %(brand)s, %(category)s, %(created_at)s, %(updated_at)s, %(primary_image)s)]
[parameters: {'asin': 'B0C3RF3HT3', 'title': 'hp 15, 13th gen intel core i3-1315u, 8gb ddr4, 512gb ssd, win 11, office 21, grey, 1.59kg, anti-glare, micro-edge,15.6-inch39.6cm, fhd laptop, intel uhd graphics, 1080p fhd camera, fd0006tu', 'price': 38450.0, 'discount': 26.0, 'rating': nan, 'review_count': 153, 'brand': '\u200ehp', 'category': 'laptops', 'created_at': Timestamp('2025-04-30 16:05:46'), 'updated_at': Timestamp('2025-04-30 16:05:46'), 'primary_image': None}]
(Background on this error at: https://sqlalche.me/e/20/f405)